### ISSUE TITLE
Create Hive Script for BQ1

### ISSUE THREAD

**Issue by delaanthonio** [ez-data/ez-gender-stats#6]

**Comment by emersonargueta78** [comment]
# This is the mysql script that will generate a table for the sqoop import

USE GENDER_STATS_DB;
DROP TABLE IF EXISTS TRANSFORM;
DROP PROCEDURE IF EXISTS TRANSFORM_BQ1;
DROP VIEW IF EXISTS BQ1_TRANSFORM;

#+-+-+-+-+-+-+-+-+#
# Transform table #
# to hold data    #
# for final       #
# transform view  #
#+-+-+-+-+-+-+-+-+
create table TRANSFORM(COUNTRY_NAME VARCHAR(100),YEAR INTEGER, DATA DECIMAL(65,30));

#+-+-+-+-+-+-+-+-+#
# Procedure to    #
# transform data  #
# from first view #
#+-+-+-+-+-+-+-+-+#
DELIMITER $$
CREATE procedure TRANSFORM_BQ1(LOWER_LIM INTEGER,UPPER_LIM INTEGER) 
BEGIN 
  DECLARE YEAR_VAR integer;
  DECLARE STR varchar(30);
  SET YEAR_VAR = LOWER_LIM;
  
  WHILE YEAR_VAR <= UPPER_LIM DO
  
  SET @STR:=concat('`',YEAR_VAR,'`');
  SET @sqlText = CONCAT(
				'INSERT INTO GENDER_STATS_DB.TRANSFORM (COUNTRY_NAME,YEAR,DATA)',
				' SELECT COUNTRY_NAME,',
                YEAR_VAR,',',@STR,
                ' FROM GENDER_STATS_DB.BQ1',
                ' WHERE ',@STR,
                ' IS NOT NULL'
                );
  PREPARE stmt FROM @sqlText;
  EXECUTE stmt;
  DEALLOCATE PREPARE stmt;
  
  set YEAR_VAR = YEAR_VAR + 1;
  
  end while;
END$$
DELIMITER ;

call TRANSFORM_BQ1(2010,2016);

#+-+-+-+-+-+-+-+-+#
# Final transform #
# TABLE to sqoop  # 
#+-+-+-+-+-+-+-+-+#
CREATE TABLE BQ1_TRANSFORM AS SELECT * FROM TRANSFORM ORDER BY COUNTRY_NAME,YEAR ASC;

DROP TABLE IF EXISTS TRANSFORM;
SELECT * FROM BQ1_TRANSFORM;

**Comment by emersonargueta78** [comment]
# this hive script use a lot of map reduces not sure if I should move some of this code over to mysql
-- create table with for sqoop import output--
DROP TABLE IF EXISTS GENDER_STATS_DB.BQ1;
CREATE EXTERNAL TABLE GENDER_STATS_DB.BQ1
(COUNTRY_NAME STRING, YEAR_COL INT, DATA_COL DECIMAL(38,30))
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '|'
TBLPROPERTIES("skip.header.line.count"="1");

--Load data from sqoop import output --
LOAD LOCAL DATA INPATH '/home/cloudera/BQ1/part-m-00000' INTO TABLE GENDER_STATS_DB.BQ1;

-- calculate the averages for each country
DROP VIEW IF EXISTS GENDER_STATS_DB.BQ1_AVERAGES;
CREATE VIEW GENDER_STATS_DB.BQ1_AVERAGES AS 
SELECT COUNTRY_NAME,AVG(DATA_COL) AS AVERAGE FROM GENDER_STATS_DB.BQ1
GROUP BY COUNTRY_NAME
ORDER BY COUNTRY_NAME ASC;

-- show only records with countries that the average is less than 30
DROP TABLE IF EXISTS GENDER_STATS_DB.BQ1_AVERAGES_LESS_30;
CREATE TABLE GENDER_STATS_DB.BQ1_AVERAGES_LESS_30 AS SELECT * FROM GENDER_STATS_DB.BQ1_AVERAGES
WHERE AVERAGE < 30;

-- show only countries where in any year the percentage was less than 30
DROP TABLE IF EXISTS BQ1_LESS_30;
CREATE TABLE BQ1_LESS_30 AS 
SELECT country_name,count(data_col) AS DATA_COUNT FROM gender_stats_db.bq1
WHERE data_col < 30
GROUP BY country_name
ORDER BY COUNTRY_NAME ASC;


--SELECT * FROM gender_stats_db.bq1_less_30 ORDER BY country_name ASC;
--SELECT * FROM gender_stats_db.bq1_averages_less_30;
